apiVersion: batch/v1
kind: Job
metadata:
  name: omabank-db-migration
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      serviceAccountName: omabank-api-sa
      restartPolicy: Never
      containers:
      - name: alembic
        image: omabankacrdev923.azurecr.io/omabank-api:latest
        imagePullPolicy: Always
        workingDir: /app
        # Explicitly pass the alembic ini path
        command: ["/usr/bin/python3", "-m", "alembic", "-c", "/app/alembic.ini", "upgrade", "head"]
        envFrom:
        - secretRef:
            name: omabank-api-secret-generated