apiVersion: batch/v1
kind: Job
metadata:
  name: omabank-db-migration
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      serviceAccountName: omabank-api-sa
      restartPolicy: Never
      containers:
      - name: alembic
        image: omabankacrdev923.azurecr.io/omabank-api:latest
        imagePullPolicy: Always

        # 1. Instructs K8s to step into the /app folder where the python code actually is
        workingDir: /app 
        
        # 2. Uses the correct distroless absolute path to execute the python module safely
        command: ["/usr/bin/python3", "-m", "alembic", "upgrade", "head"]

        envFrom:
        - secretRef:
            name: omabank-api-secret-generated