apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: omabank-tls
  namespace: default
spec:
  secretName: omabank-tls-secret
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
  - "20.87.253.92.nip.io"
