apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: azure-kv-store
spec:
  provider:
    azurekv:
      authType: WorkloadIdentity
      vaultUrl: "https://omabankkv-dev-923.vault.azure.net/"
      serviceAccountRef:
        name: omabank-api-sa
        namespace: default