apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-admin-external-secret
  namespace: default
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: azure-kv-store
    kind: ClusterSecretStore
  target:
    name: grafana-admin-secret
    creationPolicy: Owner
    template:
      data:
        admin-password: "{{ .grafanaAdminPassword }}"
        admin-user: "admin"
  data:
  - secretKey: grafanaAdminPassword
    remoteRef:
      key: grafana-admin-password
