apiVersion: v1
kind: ServiceAccount
metadata:
  name: omabank-api-sa
  namespace: default
  annotations:
    azure.workload.identity/client-id: "361af593-f23d-4f24-8b47-e0d2f2c53470"
  labels:
    azure.workload.identity/use: "true"